import { Platform, StyleSheet } from 'react-native';

export const colors = {
  ink: '#10233F',
  muted: '#60718A',
  blue: '#2667FF',
  blueSoft: '#EAF0FF',
  coral: '#FF6B5E',
  coralSoft: '#FFF0ED',
  cream: '#F7F9FC',
  white: '#FFFFFF',
  line: '#E4EAF2',
  green: '#1E9B74',
  greenSoft: '#E7F7F1',
};

export const styles = StyleSheet.create({
  webBackdrop: { flex: 1, backgroundColor: Platform.OS === 'web' ? '#DDE7F5' : colors.white, alignItems: 'center' },
  safe: { flex: 1, width: '100%', maxWidth: 520, backgroundColor: colors.white },
  appShell: { flex: 1, backgroundColor: colors.cream },
  content: { flex: 1 },
  flexBody: { flex: 1 },
  scrollPad: { paddingBottom: 18 },
  onboarding: { flex: 1, paddingHorizontal: 24, paddingTop: Platform.OS === 'android' ? 28 : 12, backgroundColor: colors.white },
  brandRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
  logoMark: { width: 26, height: 26, borderRadius: 8, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center', marginRight: 9, transform: [{ rotate: '12deg' }] },
  logoDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.coral },
  brand: { fontSize: 12, letterSpacing: 1.5, fontWeight: '900', color: colors.ink },
  stepLabel: { marginLeft: 'auto', color: colors.muted, fontSize: 12, fontWeight: '700' },
  progressRow: { flexDirection: 'row', gap: 6, marginTop: 4, marginBottom: 26 },
  progressPill: { flex: 1, height: 4, borderRadius: 4, backgroundColor: colors.line },
  progressActive: { backgroundColor: colors.coral },
  heroArt: { height: 255, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  heroCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      web: { boxShadow: '0 12px 24px rgba(38, 103, 255, 0.24)' },
      default: { shadowColor: colors.blue, shadowOpacity: 0.24, shadowRadius: 24, shadowOffset: { width: 0, height: 12 } },
    }),
  },
  heroSymbol: { color: colors.white, fontSize: 62 },
  orbitLarge: { position: 'absolute', width: 220, height: 220, borderRadius: 110, borderWidth: 1, borderColor: '#C9D7FF' },
  orbitSmall: { position: 'absolute', width: 180, height: 180, borderRadius: 90, borderWidth: 1, borderColor: colors.coral, transform: [{ rotate: '30deg' }] },
  spark: { position: 'absolute', width: 12, height: 12, borderRadius: 6, backgroundColor: colors.coral },
  eyebrow: { color: colors.coral, fontSize: 12, fontWeight: '900', letterSpacing: 1.8, marginBottom: 10 },
  display: { color: colors.ink, fontSize: 40, lineHeight: 44, fontWeight: '900', letterSpacing: -1.5, marginBottom: 14 },
  title: { color: colors.ink, fontSize: 34, lineHeight: 39, fontWeight: '900', letterSpacing: -1, marginBottom: 12 },
  lead: { color: colors.muted, fontSize: 16, lineHeight: 24, marginBottom: 24 },
  pageLead: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: 8, marginBottom: 24 },
  bottomActions: { flexDirection: 'row', gap: 12, paddingVertical: 18, alignItems: 'center' },
  actionFill: { flex: 1 },
  button: { minHeight: 56, backgroundColor: colors.blue, borderRadius: 16, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 },
  buttonSecondary: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line },
  buttonText: { color: colors.white, fontWeight: '800', fontSize: 16 },
  buttonSecondaryText: { color: colors.ink },
  buttonArrow: { color: colors.white, fontSize: 21 },
  pressed: { opacity: 0.75, transform: [{ scale: 0.99 }] },
  backButton: { minHeight: 56, justifyContent: 'center', paddingRight: 8 },
  backText: { color: colors.ink, fontWeight: '800' },
  choiceList: { gap: 12 },
  choice: { minHeight: 82, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.white },
  choiceSelected: { borderColor: colors.blue, borderWidth: 2, backgroundColor: colors.blueSoft },
  choiceIcon: { width: 46, height: 46, borderRadius: 14, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', marginRight: 13 },
  choiceIconSelected: { backgroundColor: colors.blue },
  choiceIconText: { fontSize: 22, color: colors.ink, fontWeight: '900' },
  whiteText: { color: colors.white },
  choiceCopy: { flex: 1 },
  choiceTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', marginBottom: 3 },
  choiceBody: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: '#B5C0CF', alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  radioSelected: { borderColor: colors.blue },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.blue },
  inputLabel: { color: colors.ink, fontSize: 11, fontWeight: '900', letterSpacing: 1.4, marginTop: 8, marginBottom: 9 },
  input: { minHeight: 60, borderWidth: 1, borderColor: '#C9D3E0', borderRadius: 16, paddingHorizontal: 18, paddingVertical: 16, fontSize: 17, color: colors.ink, backgroundColor: colors.white, marginBottom: 18 },
  promiseCard: { flexDirection: 'row', borderRadius: 18, backgroundColor: colors.greenSoft, padding: 18, marginTop: 14 },
  promiseIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.green, color: colors.white, textAlign: 'center', lineHeight: 32, fontWeight: '900', marginRight: 12 },
  promiseCopy: { flex: 1 },
  promiseTitle: { color: colors.ink, fontWeight: '800', marginBottom: 4 },
  promiseBody: { color: colors.muted, lineHeight: 20 },
  planHero: { backgroundColor: colors.blue, borderRadius: 26, padding: 24, marginTop: 4, marginBottom: 14 },
  planLabel: { color: '#BFD0FF', fontSize: 11, letterSpacing: 1.6, fontWeight: '900' },
  planTitle: { color: colors.white, fontSize: 28, lineHeight: 33, fontWeight: '900', marginTop: 11 },
  planRule: { width: 44, height: 4, backgroundColor: colors.coral, borderRadius: 2, marginVertical: 19 },
  planQuote: { color: colors.white, fontSize: 16, lineHeight: 24, fontStyle: 'italic' },
  miniRow: { flexDirection: 'row', gap: 12 },
  miniCard: { flex: 1, borderRadius: 18, backgroundColor: colors.cream, padding: 16 },
  miniNumber: { color: colors.coral, fontSize: 11, fontWeight: '900' },
  miniTitle: { color: colors.ink, fontWeight: '800', marginTop: 10, marginBottom: 4 },
  miniBody: { color: colors.muted, lineHeight: 18, fontSize: 13 },
  disclaimer: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 16 },
  dashboardPad: { padding: 22, paddingBottom: 34 },
  topRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 22 },
  kicker: { color: colors.coral, fontSize: 11, letterSpacing: 1.7, fontWeight: '900', marginBottom: 4 },
  dashTitle: { color: colors.ink, fontSize: 30, lineHeight: 35, fontWeight: '900', letterSpacing: -0.8 },
  avatar: { marginLeft: 'auto', width: 46, height: 46, borderRadius: 15, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.white, fontSize: 18, fontWeight: '900' },
  online: { position: 'absolute', width: 11, height: 11, borderRadius: 6, backgroundColor: colors.green, borderWidth: 2, borderColor: colors.white, right: -2, bottom: -2 },
  momentumCard: { backgroundColor: colors.blue, borderRadius: 24, padding: 20, flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  momentumCopy: { flex: 1, paddingRight: 10 },
  cardKicker: { color: '#C8D6FF', fontSize: 10, letterSpacing: 1.4, fontWeight: '900' },
  momentumTitle: { color: colors.white, fontSize: 21, lineHeight: 26, fontWeight: '900', marginVertical: 8 },
  momentumBody: { color: '#DCE5FF', fontSize: 13, lineHeight: 18 },
  ring: { width: 88, height: 88, borderRadius: 44, borderWidth: 8, borderColor: colors.coral, alignItems: 'center', justifyContent: 'center', backgroundColor: '#487EFF' },
  ringInner: { alignItems: 'center' },
  ringValue: { color: colors.white, fontWeight: '900', fontSize: 19 },
  ringLabel: { color: '#DCE5FF', fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  celebrate: { backgroundColor: colors.greenSoft, borderRadius: 18, padding: 16, marginBottom: 22 },
  celebrateTitle: { color: colors.green, fontWeight: '900', marginBottom: 4 },
  celebrateBody: { color: colors.muted, lineHeight: 20 },
  sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '900', marginBottom: 12 },
  sectionMeta: { color: colors.blue, fontSize: 10, letterSpacing: 1.2, fontWeight: '900' },
  habitCard: { backgroundColor: colors.white, borderRadius: 20, paddingHorizontal: 16, marginBottom: 28, borderWidth: 1, borderColor: colors.line },
  habitRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center' },
  rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.line },
  check: { width: 28, height: 28, borderRadius: 9, borderWidth: 2, borderColor: '#C2CCDA', alignItems: 'center', justifyContent: 'center', marginRight: 13 },
  checkDone: { backgroundColor: colors.green, borderColor: colors.green },
  checkText: { color: colors.white, fontWeight: '900' },
  habitCopy: { flex: 1 },
  habitTitle: { color: colors.ink, fontWeight: '700', marginBottom: 5 },
  strike: { color: colors.muted, textDecorationLine: 'line-through' },
  habitTime: { color: colors.muted, fontSize: 12 },
  chevron: { color: '#A5B1C0', fontSize: 28 },
  moodCard: { backgroundColor: colors.white, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: colors.line, marginBottom: 28 },
  moodQuestion: { color: colors.ink, fontWeight: '800', marginBottom: 16 },
  moodRow: { flexDirection: 'row', justifyContent: 'space-between' },
  moodItem: { alignItems: 'center', flex: 1 },
  moodDot: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', marginBottom: 7 },
  moodActive: { backgroundColor: colors.coral },
  moodFace: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  moodLabel: { color: colors.muted, fontSize: 10 },
  moodLabelActive: { color: colors.coral, fontWeight: '900' },
  coachCard: { backgroundColor: colors.coralSoft, borderRadius: 22, padding: 19, flexDirection: 'row' },
  coachBadge: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.coral, alignItems: 'center', justifyContent: 'center', marginRight: 13 },
  coachCopy: { flex: 1 },
  coachKicker: { color: colors.coral, fontSize: 10, letterSpacing: 1.2, fontWeight: '900' },
  coachTitle: { color: colors.ink, fontSize: 18, fontWeight: '900', marginVertical: 7 },
  coachBody: { color: colors.muted, lineHeight: 20, fontSize: 13 },
  coachLink: { color: colors.blue, fontWeight: '800', marginTop: 12 },
  footerNote: { color: colors.muted, fontSize: 10, textAlign: 'center', marginTop: 20 },
  tabBar: { height: 76, flexDirection: 'row', backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.line, paddingBottom: Platform.OS === 'ios' ? 8 : 2 },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabIcon: { color: '#8492A5', fontSize: 22, marginBottom: 3 },
  tabText: { color: '#8492A5', fontSize: 10, fontWeight: '700' },
  tabActive: { color: colors.blue },
  tabIndicator: { position: 'absolute', top: 0, width: 26, height: 3, borderRadius: 2, backgroundColor: colors.blue },
  goalFeature: { backgroundColor: colors.coral, borderRadius: 24, padding: 22, marginBottom: 26 },
  goalFeatureLabel: { color: '#FFE1DC', fontSize: 10, letterSpacing: 1.5, fontWeight: '900' },
  goalFeatureTitle: { color: colors.white, fontSize: 25, lineHeight: 30, fontWeight: '900', marginVertical: 9 },
  goalFeatureBody: { color: '#FFF0ED', lineHeight: 20 },
  goalProgress: { height: 7, backgroundColor: '#E95549', borderRadius: 4, marginTop: 20, overflow: 'hidden' },
  goalProgressFill: { height: 7, backgroundColor: colors.white, borderRadius: 4 },
  goalProgressText: { color: colors.white, fontSize: 9, fontWeight: '900', letterSpacing: 1.1, marginTop: 7 },
  goalGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 22 },
  goalTile: { width: '48.5%', minHeight: 145, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 16 },
  goalTileActive: { borderColor: colors.blue, borderWidth: 2, backgroundColor: colors.blueSoft },
  goalTileIcon: { color: colors.coral, fontSize: 24, fontWeight: '900' },
  blueText: { color: colors.blue },
  goalTileTitle: { color: colors.ink, fontWeight: '900', fontSize: 16, marginTop: 12, marginBottom: 5 },
  goalTileBody: { color: colors.muted, lineHeight: 17, fontSize: 12 },
  customChip: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 16, padding: 14, marginBottom: 10 },
  customChipActive: { borderColor: colors.coral, backgroundColor: colors.coralSoft },
  customChipTitle: { color: colors.ink, fontWeight: '800' },
  emptyCard: { borderWidth: 1, borderStyle: 'dashed', borderColor: colors.line, borderRadius: 18, padding: 18, marginBottom: 18 },
  emptyTitle: { color: colors.ink, fontWeight: '800', marginBottom: 6 },
  emptyBody: { color: colors.muted, lineHeight: 20 },
  streakCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.blue, borderRadius: 22, padding: 20, marginBottom: 16 },
  streakNumber: { color: colors.white, fontSize: 48, fontWeight: '900', marginRight: 16 },
  streakTitle: { color: colors.white, fontSize: 18, fontWeight: '900' },
  streakBody: { color: '#DCE5FF', marginTop: 4 },
  chartCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 22, padding: 18, marginBottom: 16 },
  greenText: { color: colors.green, fontWeight: '900' },
  chart: { height: 120, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around' },
  barWrap: { alignItems: 'center', justifyContent: 'flex-end', height: 110 },
  bar: { width: 19, backgroundColor: '#C8D6FF', borderRadius: 7 },
  barHighlight: { backgroundColor: colors.coral },
  barLabel: { color: colors.muted, fontSize: 10, marginTop: 7 },
  insightCard: { backgroundColor: colors.greenSoft, borderRadius: 22, padding: 20, marginBottom: 16 },
  insightCardWhite: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 22, padding: 20 },
  insightTag: { color: colors.green, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 },
  insightTagBlue: { color: colors.blue, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 },
  insightTitle: { color: colors.ink, fontSize: 20, lineHeight: 25, fontWeight: '900', marginVertical: 8 },
  insightBody: { color: colors.muted, lineHeight: 21, marginBottom: 15 },
  profileHero: { alignItems: 'center', backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 22, padding: 24, marginVertical: 22 },
  profileAvatar: { width: 78, height: 78, borderRadius: 25, backgroundColor: colors.coral, alignItems: 'center', justifyContent: 'center' },
  profileInitial: { color: colors.white, fontSize: 34, fontWeight: '900' },
  profileName: { color: colors.ink, fontSize: 22, fontWeight: '900', marginTop: 13 },
  profileSince: { color: colors.muted, marginTop: 5, fontSize: 13 },
  settingsRow: { minHeight: 58, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.line, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' },
  settingsText: { flex: 1, color: colors.ink, fontWeight: '700' },
  disclaimerCard: { backgroundColor: colors.coralSoft, borderRadius: 18, padding: 17, marginVertical: 20 },
  disclaimerTitle: { color: colors.ink, fontWeight: '900', marginBottom: 6 },
  disclaimerBody: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  sheet: { flex: 1, backgroundColor: colors.cream },
  sheetHead: { paddingHorizontal: 22, paddingTop: 18, paddingBottom: 8, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.line },
  sheetKicker: { color: colors.coral, fontSize: 11, fontWeight: '900', letterSpacing: 1.4 },
  sheetTitle: { color: colors.ink, fontSize: 28, fontWeight: '900', marginTop: 6, marginBottom: 10 },
  article: { backgroundColor: colors.white, borderRadius: 22, padding: 20, marginBottom: 16, borderWidth: 1, borderColor: colors.line },
  articleStep: { color: colors.blue, fontWeight: '900', fontSize: 12, letterSpacing: 1.2, marginBottom: 8 },
  articleTitle: { color: colors.ink, fontSize: 18, fontWeight: '900', marginBottom: 8 },
  articleBody: { color: colors.muted, lineHeight: 22 },
  toast: { backgroundColor: colors.green, borderRadius: 16, padding: 16, marginBottom: 16 },
  toastText: { color: colors.white, fontWeight: '800' },
  skip: { alignSelf: 'center', minHeight: 44, justifyContent: 'center' },
  skipText: { color: colors.blue, fontWeight: '800' },
});
